//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingBonPutih.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class datum
    {
        public int ID_BAR { get; set; }
        public string BP { get; set; }
        public string AMOUNT { get; set; }
        public string SEN { get; set; }
        public int ID_CUR { get; set; }
        public string AMOUNT_SHOW { get; set; }
        public string TERBILANG { get; set; }
        public string SP { get; set; }
        public int ID_DEP { get; set; }
        public int ID_RULES { get; set; }
        public System.DateTime TGL_INPUT { get; set; }
        public Nullable<System.DateTime> TGL_STRUK { get; set; }
        public Nullable<System.DateTime> TGL_ARCHIVED { get; set; }
        public Nullable<System.DateTime> TGL_REJECTED { get; set; }
        public string KEPADA { get; set; }
        public string POS1 { get; set; }
        public string POS2 { get; set; }
        public string POS3 { get; set; }
        public string POS4 { get; set; }
        public string POS5 { get; set; }
        public string POS6 { get; set; }
        public string POS7 { get; set; }
        public string POS8 { get; set; }
        public string POS9 { get; set; }
        public string POS10 { get; set; }
        public string POS_ARCHIVE { get; set; }
        public string POS_REJECT { get; set; }
        public string NOW_POS { get; set; }
        public string NEXT_POS { get; set; }
        public int LAST_POS { get; set; }
        public string FROM_POS { get; set; }
        public string KET { get; set; }
        public string KET_BP { get; set; }
        public string BARCODE { get; set; }
        public string USER { get; set; }
        public int STATUS { get; set; }
        public string BEBAN { get; set; }
        public Nullable<System.DateTime> TGL_JT { get; set; }
        public Nullable<System.DateTime> TGL_SKRNG { get; set; }
        public string PIMPINAN { get; set; }
        public string PEMOHON { get; set; }
        public Nullable<int> PRINT_TT { get; set; }
        public Nullable<int> STRUK_READY { get; set; }
        public Nullable<int> STATUS_VER { get; set; }
        public string MODIFIED_BY { get; set; }
        public Nullable<System.DateTime> MODIFIED_ON { get; set; }
        public string FILENAME { get; set; }
        public Nullable<int> UPDATE_COUNT { get; set; }
    }
}
