//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingBonPutih.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class departeman
    {
        public int ID_DEP { get; set; }
        public string NAMA_DEP { get; set; }
        public int FLAG_DEP { get; set; }
        public int SAP_DEP { get; set; }
    }
}
