//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingBonPutih.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class detil
    {
        public int ID_DETIL { get; set; }
        public string BARCODE { get; set; }
        public string PERKIRAAN { get; set; }
        public string KETERANGAN { get; set; }
        public long JUMLAH { get; set; }
        public string JUMLAH_SEN { get; set; }
    }
}
