//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingBonPutih.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class sp
    {
        public string SP1 { get; set; }
        public string USER_SP { get; set; }
        public int SP_PRINT { get; set; }
        public System.DateTime SP_NOW { get; set; }
    }
}
