//------------------------------------------------------------------------------
// <auto-generated>
//    This code was generated from a template.
//
//    Manual changes to this file may cause unexpected behavior in your application.
//    Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TrackingBonPutih.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class t_terima
    {
        public string NO_TT { get; set; }
        public string USER_TT { get; set; }
        public Nullable<int> ID_POS { get; set; }
        public string TT_PRINT { get; set; }
        public string ARCHIVED { get; set; }
        public string REJECTED { get; set; }
        public System.DateTime TT_NOW { get; set; }
    }
}
